### ISSUE TITLE
Problems with receiver.py

### ISSUE THREAD

**Issue by matthias33890** [George-iam/Midjourney_api#12]
Thank you first of all for this project. It is exactly what I need.
I have following Problems:

1. I can't find the authorization key in my payload. Is it needed?

2. When I start receiver.py I get following error:

`=========== listening started ===========
Traceback (most recent call last):
  File "/Users/matthias/Library/receiver.py", line 133, in <module>
    receiver.main()
  File "/Users/matthias/Library/receiver.py", line 110, in main
    self.collecting_results()
  File "/Users/matthias/Library/receiver.py", line 49, in collecting_results
    if (message['author']['username'] == 'Midjourney Bot') and ('**' in message['content']):
TypeError: string indices must be integers`

I wasn't able to solve it.

I hope you can help me!

**Comment by George-iam** [comment]
Hi!
Off course you need it, that's why you got this error.
Take a look at all the instruction steps I provided.

**Comment by matthias33890** [comment]
I followed your instructions.
![93DE3F7D-8362-4C19-B0BA-9954A890C7AE_1_201_a](https://user-images.githubusercontent.com/125920740/235245059-2f28b1e3-d881-41b1-ac29-7077d2a96222.jpeg)

But in my payload I don't have the authorization key.

**Comment by matthias33890** [comment]
I solved my problem, you can get the authorization key in the Headers of the https request.
