### ISSUE TITLE
大佬们，请问第八步在命令行里操作后显示“can't open file '//path/to/cloned/dir/sender.py': [Errno 2] No such file or directory”啥意思？？

### ISSUE THREAD

**Issue by qq460046000** [George-iam/Midjourney_api#15]
XXX@jiqi midjourney_api % python /path/to/cloned/dir/sender.py --params /path/to/cloned/dir/sender_params.json --prompt 'a boy'           
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: can't open file '/path/to/cloned/dir/sender.py': [Errno 2] No such file or directory

**Comment by George-iam** [comment]
'/path/to/cloned/dir/ mean you need to replace it with a path to a folder you cloned this repo to.
