### ISSUE TITLE
How to get correspondence between command and image ?

### ISSUE THREAD

**Issue by jiangying000** [George-iam/Midjourney_api#5]

**Comment by George-iam** [comment]
There is no way to do it directly, but you can do it through filename - Midjourney internal api creates filenames using your prompt by replacing spaces with '_'. And if you send more than one identical prompts so you'll get the same number of files named with this prompt, so you can remove files one by one from your local folder after each using of image.

**Comment by jiangying000** [comment]
Seems we may unable to download file due to Midjourney change the input image url ?

If we use `https://i.pinimg.com/564x/66/a8/8d/66a88dd43ddd068939aa01c3b67a1811.jpg dreamy haze` as prompt, midjourney would change url `https://i.pinimg.com/564x/66/a8/8d/66a88dd43ddd068939aa01c3b67a1811.jpg` to `https://s.mj.run/PhrIwPntq4s` 

and the attachment name does not contain url at all
